### ISSUE TITLE
ImportError: cannot import name empty_iter

### ISSUE THREAD

**Issue by oppianmatt** [InviteBox/django-live-profiler#24]
```
  File "[...]/venv/lib/python2.7/site-packages/profiler/models.py", line 5, in <module>
    from profiler.instrument import *
  File "[...]/venv/lib/python2.7/site-packages/profiler/instrument.py", line 3, in <module>
    from django.db.models.sql.compiler import SQLCompiler, empty_iter
ImportError: cannot import name empty_iter
```

**Comment by markeroon** [comment]
I'm having this issue too. I noticed that my build choked on zeromq at some point. Possibly related?

**Comment by oppianmatt** [comment]
Issue is that empty_iter got moved in a django upgrade and so this won't work with django 1.6 or above.

**Comment by markeroon** [comment]
@oppianmatt Is this project dead, for all intents and purposes? Should I use something different?

**Comment by cool-RR** [comment]
I'm stuck because of this issue too.

**Comment by oppianmatt** [comment]
Yep I think this project is dead. I've moved to using runprofileserver which creates prof files and use a view to view them:

http://django-extensions.readthedocs.org/en/latest/runprofileserver.html

**Comment by markeroon** [comment]
Nice, thanks for the link.

**Comment by pirate** [comment]
Fixed here: https://github.com/InviteBox/django-live-profiler/pull/28

I just replaced it with `QuerySet.none()`.
